name: Convert README.md to index.html

on:
  push:
    paths:
      - README.md

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Convert README.md to index.html
        run: |
          mkdir -p output
          pandoc README.md -o output/index.html

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add output/index.html
          git commit -m "Update index.html from README.md" || echo "No changes to commit"
          git push

